
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localbite
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform : org.hibernate.dialect.PostgreSQLDialect

  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
      max-age: 3600
      allowed-headers: "Requestor-Type"
      exposed-headers: "X-Get-Header"
